export const isoAmtContent = {
  slug: 'iso-amt',
  title: 'ISO Exercise AMT Calculator',
  metaTitle: 'ISO Exercise AMT Calculator (2025–2026)',
  metaDescription:
    'Free calculator that estimates the Alternative Minimum Tax owed when you exercise incentive stock options (ISOs) — exercise-and-hold vs. same-year sale, with AMT credit carryforward.',
  h1: 'ISO Exercise AMT Calculator',
  lede:
    'Exercising ISOs and holding them creates an AMT bill that can dwarf your salary. Same-day-sale skips AMT but loses the long-term capital-gain treatment. Enter your strike, FMV, and shares to see both paths and the cash you’ll need.',
  lastUpdated: '2026-05-10',
  taxYearDefault: 2026,
  howToSteps: [
    {
      name: 'Enter your grant details',
      text: 'Type the strike price, the current 409A / FMV per share, and how many options you plan to exercise.',
    },
    {
      name: 'Choose a scenario',
      text: 'Exercise-and-hold (start the LTCG clock + trigger AMT) or exercise-and-sell-same-year (no AMT, but the bargain becomes ordinary W-2 income).',
    },
    {
      name: 'Add your wages and state',
      text: 'YTD wages and pre-tax deductions size your AMT exemption phaseout and marginal rates. State tax applies on the same-year-sale path.',
    },
    {
      name: 'Read AMT owed, cash needed, and credit carryforward',
      text: 'You’ll see the bargain element, AMTI, AMT exemption available, tentative minimum tax, regular tax, and the AMT credit you’ll carry forward to offset future regular tax.',
    },
  ],
  faqs: [
    {
      q: 'What is AMT and why do ISOs trigger it?',
      a: 'The Alternative Minimum Tax is a parallel tax system (IRC §55) designed to ensure high earners pay a minimum amount. ISO exercises are an "AMT preference item" under IRC §56(b)(3): the bargain element (FMV minus strike, times shares) is included in AMT income even though it is NOT included in regular taxable income. If your tentative minimum tax exceeds your regular federal tax, the difference is AMT owed. You report it on Form 6251, line 2i.',
    },
    {
      q: 'How is the bargain element calculated?',
      a: '(FMV at exercise − strike price) × number of shares exercised. For pre-IPO companies, FMV is typically the most recent 409A valuation. For public companies, it’s the trading price on the exercise date. Brokers report ISO exercises on Form 3921, which the IRS cross-references with your return.',
    },
    {
      q: 'What is the AMT credit carryforward?',
      a: 'AMT generated by an ISO exercise is a "deferral preference" under IRC §53. The IRS gives you a Minimum Tax Credit equal to the AMT paid, claimable on Form 8801. You apply the credit in future years when your regular federal tax exceeds your tentative minimum tax. In practice, many people recover the full credit over 1–5 years.',
    },
    {
      q: 'Why might exercise-and-hold be worth the AMT?',
      a: 'If you hold the shares >1 year from exercise AND >2 years from grant before selling (qualifying disposition under IRC §422(a)), the entire gain (sale − strike) is taxed as long-term capital gain — typically 15% or 20% federal vs. up to 37% ordinary. The AMT you paid generates a credit you mostly recover. Net result: you can save 10–22 percentage points of federal tax on the appreciation.',
    },
    {
      q: 'When does same-year sale make sense?',
      a: 'When you don’t have the cash to pay AMT, when the stock is illiquid (private company), when you’re skeptical the price will hold, or when the bargain element is small enough that the LTCG savings aren’t worth the AMT cash crunch. Same-year sale (a disqualifying disposition under IRC §421(b)) converts the bargain to ordinary income and removes the AMT preference entirely.',
    },
    {
      q: 'Does this include California AMT?',
      a: 'Not in v1. California has its own AMT (CA Rev. & Tax Code §17062, ~7% on ISO bargain element above the CA exemption — see CA Schedule P (540)). If you’re in CA, plan for an additional ~7% of the bargain element on top of federal AMT. We surface this as a note in the calculator.',
    },
    {
      q: 'What is the $100k ISO limit?',
      a: 'IRC §422(d) limits the FMV of ISO grants that become exercisable in a single calendar year to $100,000 per employee (measured at grant-date FMV × shares). Anything above that is automatically reclassified as NSO. The calculator does not enforce this limit — confirm with your equity team or look at your stock-plan documents.',
    },
    {
      q: 'Is this tax advice?',
      a: 'No — it’s an estimate based on IRS Form 6251 instructions, IRC §§55–56 and §422, and your inputs. It does not consider state AMT, multi-state residency, NQDC interactions, foreign tax credits, multi-year ISO planning, or AMT credit recapture. ISO exercise decisions should be reviewed by a CPA experienced with equity comp.',
    },
  ],
} as const;
