/**
 * State-by-state stock-comp tax reference data.
 *
 * Sources:
 *  - Top marginal rates: Tax Foundation 2025 state individual income tax brackets summary.
 *  - CA supplemental rate (10.23%) + CA AMT: California FTB Pub 1004 + Schedule P (540).
 *  - NY supplemental rate (11.7%): NY DTF Pub NYS-50.
 *  - State personal-AMT status: Tax Foundation "States that have personal AMT" (only CA still
 *    has a routinely-applied personal AMT post-2022; others either repealed or are dormant).
 *
 * IMPORTANT: This is a planning reference, not tax advice. States amend code annually.
 * Each page links to the state revenue department for current rules.
 */

export interface StateStockCompProfile {
  code: string;
  name: string;
  /** Top marginal personal income tax rate, fraction. */
  topMarginalRate: number;
  /** Supplemental wage withholding rate, fraction. Null = uses top marginal as default. */
  supplementalRate: number | null;
  /** True if the state imposes a personal AMT that can affect ISO exercises. */
  hasPersonalAmt: boolean;
  /** True if the state taxes long-term capital gain at ordinary rates (most do). */
  taxesLtcgAsOrdinary: boolean;
  /** State revenue department URL (linked from the page). */
  revenueDeptUrl: string;
  /** Friendly label for the state revenue dept. */
  revenueDeptLabel: string;
  /** Optional state-specific notes. */
  notes?: string;
}

const NO_TAX_NOTE =
  'No state personal income tax. RSU, ESPP, and ISO income are not taxed at the state level for residents — though multi-state allocation may still apply if you worked in another state during the vesting period.';

export const stateStockCompProfiles: StateStockCompProfile[] = [
  {
    code: 'AL',
    name: 'Alabama',
    topMarginalRate: 0.05,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.revenue.alabama.gov/',
    revenueDeptLabel: 'Alabama Department of Revenue',
  },
  {
    code: 'AK',
    name: 'Alaska',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://tax.alaska.gov/',
    revenueDeptLabel: 'Alaska Department of Revenue',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'AZ',
    name: 'Arizona',
    topMarginalRate: 0.025,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://azdor.gov/',
    revenueDeptLabel: 'Arizona Department of Revenue',
    notes: 'Arizona uses a flat 2.5% individual income tax (post-2023 reform).',
  },
  {
    code: 'AR',
    name: 'Arkansas',
    topMarginalRate: 0.039,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://www.dfa.arkansas.gov/income-tax',
    revenueDeptLabel: 'Arkansas Department of Finance and Administration',
    notes:
      'Arkansas allows a 50% capital-gains exclusion on net long-term capital gains, reducing the effective state LTCG rate.',
  },
  {
    code: 'CA',
    name: 'California',
    topMarginalRate: 0.123,
    supplementalRate: 0.1023,
    hasPersonalAmt: true,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.ftb.ca.gov/',
    revenueDeptLabel: 'California Franchise Tax Board',
    notes:
      'California has a personal AMT (Schedule P (540), ~7%) that adds onto federal AMT for ISO exercises. A 1% Mental Health Services Tax surcharge applies to taxable income above $1M. Stock-option / RSU supplemental withholding is 10.23% (FTB Pub DE 44).',
  },
  {
    code: 'CO',
    name: 'Colorado',
    topMarginalRate: 0.044,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.colorado.gov/',
    revenueDeptLabel: 'Colorado Department of Revenue',
    notes: 'Colorado uses a flat 4.4% rate.',
  },
  {
    code: 'CT',
    name: 'Connecticut',
    topMarginalRate: 0.0699,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://portal.ct.gov/DRS',
    revenueDeptLabel: 'Connecticut Department of Revenue Services',
  },
  {
    code: 'DE',
    name: 'Delaware',
    topMarginalRate: 0.066,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://revenue.delaware.gov/',
    revenueDeptLabel: 'Delaware Division of Revenue',
  },
  {
    code: 'DC',
    name: 'District of Columbia',
    topMarginalRate: 0.1075,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://otr.cfo.dc.gov/',
    revenueDeptLabel: 'DC Office of Tax and Revenue',
  },
  {
    code: 'FL',
    name: 'Florida',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://floridarevenue.com/',
    revenueDeptLabel: 'Florida Department of Revenue',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'GA',
    name: 'Georgia',
    topMarginalRate: 0.0539,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://dor.georgia.gov/',
    revenueDeptLabel: 'Georgia Department of Revenue',
    notes: 'Georgia is transitioning to a flat tax; rates may change year-over-year.',
  },
  {
    code: 'HI',
    name: 'Hawaii',
    topMarginalRate: 0.11,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.hawaii.gov/',
    revenueDeptLabel: 'Hawaii Department of Taxation',
  },
  {
    code: 'ID',
    name: 'Idaho',
    topMarginalRate: 0.058,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.idaho.gov/',
    revenueDeptLabel: 'Idaho State Tax Commission',
  },
  {
    code: 'IL',
    name: 'Illinois',
    topMarginalRate: 0.0495,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.illinois.gov/',
    revenueDeptLabel: 'Illinois Department of Revenue',
    notes: 'Illinois uses a flat 4.95% individual income tax rate.',
  },
  {
    code: 'IN',
    name: 'Indiana',
    topMarginalRate: 0.0305,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.in.gov/dor/',
    revenueDeptLabel: 'Indiana Department of Revenue',
    notes:
      'Indiana uses a flat state rate plus county-level income taxes that vary by county of residence.',
  },
  {
    code: 'IA',
    name: 'Iowa',
    topMarginalRate: 0.038,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.iowa.gov/',
    revenueDeptLabel: 'Iowa Department of Revenue',
    notes: 'Iowa repealed its personal AMT effective tax year 2023.',
  },
  {
    code: 'KS',
    name: 'Kansas',
    topMarginalRate: 0.057,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.ksrevenue.gov/',
    revenueDeptLabel: 'Kansas Department of Revenue',
  },
  {
    code: 'KY',
    name: 'Kentucky',
    topMarginalRate: 0.04,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://revenue.ky.gov/',
    revenueDeptLabel: 'Kentucky Department of Revenue',
    notes: 'Kentucky uses a flat 4% individual rate.',
  },
  {
    code: 'LA',
    name: 'Louisiana',
    topMarginalRate: 0.0425,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://revenue.louisiana.gov/',
    revenueDeptLabel: 'Louisiana Department of Revenue',
  },
  {
    code: 'ME',
    name: 'Maine',
    topMarginalRate: 0.0715,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.maine.gov/revenue/',
    revenueDeptLabel: 'Maine Revenue Services',
  },
  {
    code: 'MD',
    name: 'Maryland',
    topMarginalRate: 0.0575,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.marylandtaxes.gov/',
    revenueDeptLabel: 'Maryland Comptroller',
    notes:
      'Maryland adds county/local "piggyback" income taxes (typically 2.25%–3.20%) on top of the state rate.',
  },
  {
    code: 'MA',
    name: 'Massachusetts',
    topMarginalRate: 0.09,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.mass.gov/orgs/massachusetts-department-of-revenue',
    revenueDeptLabel: 'Massachusetts Department of Revenue',
    notes:
      'Massachusetts adds a 4% surtax on income above $1M (the "Fair Share Amendment"), bringing the top rate to 9% on high earners. Short-term capital gains are taxed at 8.5% in MA.',
  },
  {
    code: 'MI',
    name: 'Michigan',
    topMarginalRate: 0.0425,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.michigan.gov/treasury',
    revenueDeptLabel: 'Michigan Department of Treasury',
    notes: 'Michigan uses a flat 4.25% individual rate.',
  },
  {
    code: 'MN',
    name: 'Minnesota',
    topMarginalRate: 0.0985,
    supplementalRate: null,
    hasPersonalAmt: true,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.revenue.state.mn.us/',
    revenueDeptLabel: 'Minnesota Department of Revenue',
    notes:
      'Minnesota retains a personal AMT (Schedule M1MT) at 6.75% that can apply to ISO exercises.',
  },
  {
    code: 'MS',
    name: 'Mississippi',
    topMarginalRate: 0.044,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.dor.ms.gov/',
    revenueDeptLabel: 'Mississippi Department of Revenue',
  },
  {
    code: 'MO',
    name: 'Missouri',
    topMarginalRate: 0.047,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://dor.mo.gov/',
    revenueDeptLabel: 'Missouri Department of Revenue',
  },
  {
    code: 'MT',
    name: 'Montana',
    topMarginalRate: 0.059,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://mtrevenue.gov/',
    revenueDeptLabel: 'Montana Department of Revenue',
    notes: 'Montana provides a partial credit for net long-term capital gains.',
  },
  {
    code: 'NE',
    name: 'Nebraska',
    topMarginalRate: 0.052,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://revenue.nebraska.gov/',
    revenueDeptLabel: 'Nebraska Department of Revenue',
  },
  {
    code: 'NV',
    name: 'Nevada',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://tax.nv.gov/',
    revenueDeptLabel: 'Nevada Department of Taxation',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'NH',
    name: 'New Hampshire',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://www.revenue.nh.gov/',
    revenueDeptLabel: 'New Hampshire Department of Revenue Administration',
    notes:
      'New Hampshire taxes only interest and dividends (the I&D tax is being phased out). Wages and capital gains are not state-taxed for residents.',
  },
  {
    code: 'NJ',
    name: 'New Jersey',
    topMarginalRate: 0.1075,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.state.nj.us/treasury/taxation/',
    revenueDeptLabel: 'New Jersey Division of Taxation',
  },
  {
    code: 'NM',
    name: 'New Mexico',
    topMarginalRate: 0.059,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.tax.newmexico.gov/',
    revenueDeptLabel: 'New Mexico Taxation and Revenue Department',
  },
  {
    code: 'NY',
    name: 'New York',
    topMarginalRate: 0.109,
    supplementalRate: 0.1023,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.tax.ny.gov/',
    revenueDeptLabel: 'New York State Department of Taxation and Finance',
    notes:
      'New York supplemental withholding rate is 11.7% for high earners (NYS Pub NYS-50). NYC residents pay an additional NYC personal income tax of up to ~3.876% on top of state.',
  },
  {
    code: 'NC',
    name: 'North Carolina',
    topMarginalRate: 0.0425,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.ncdor.gov/',
    revenueDeptLabel: 'North Carolina Department of Revenue',
    notes: 'North Carolina uses a flat 4.25% rate (scheduled to decline annually).',
  },
  {
    code: 'ND',
    name: 'North Dakota',
    topMarginalRate: 0.025,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://www.tax.nd.gov/',
    revenueDeptLabel: 'North Dakota Office of State Tax Commissioner',
    notes: 'North Dakota allows a 40% net long-term capital-gain deduction.',
  },
  {
    code: 'OH',
    name: 'Ohio',
    topMarginalRate: 0.035,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.ohio.gov/',
    revenueDeptLabel: 'Ohio Department of Taxation',
  },
  {
    code: 'OK',
    name: 'Oklahoma',
    topMarginalRate: 0.0475,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://oklahoma.gov/tax.html',
    revenueDeptLabel: 'Oklahoma Tax Commission',
  },
  {
    code: 'OR',
    name: 'Oregon',
    topMarginalRate: 0.099,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.oregon.gov/dor/',
    revenueDeptLabel: 'Oregon Department of Revenue',
  },
  {
    code: 'PA',
    name: 'Pennsylvania',
    topMarginalRate: 0.0307,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.revenue.pa.gov/',
    revenueDeptLabel: 'Pennsylvania Department of Revenue',
    notes:
      'Pennsylvania uses a flat 3.07% rate. Local Earned Income Tax (EIT) of ~1%–4% applies on top depending on jurisdiction. Pennsylvania does NOT recognize §423 ESPP qualifying-disposition treatment the same way as federal — the discount may be taxed differently. Consult a PA-licensed CPA for ESPP planning.',
  },
  {
    code: 'RI',
    name: 'Rhode Island',
    topMarginalRate: 0.0599,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.ri.gov/',
    revenueDeptLabel: 'Rhode Island Division of Taxation',
  },
  {
    code: 'SC',
    name: 'South Carolina',
    topMarginalRate: 0.062,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://dor.sc.gov/',
    revenueDeptLabel: 'South Carolina Department of Revenue',
    notes: 'South Carolina allows a 44% net long-term capital-gain deduction.',
  },
  {
    code: 'SD',
    name: 'South Dakota',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://dor.sd.gov/',
    revenueDeptLabel: 'South Dakota Department of Revenue',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'TN',
    name: 'Tennessee',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://www.tn.gov/revenue.html',
    revenueDeptLabel: 'Tennessee Department of Revenue',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'TX',
    name: 'Texas',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://comptroller.texas.gov/',
    revenueDeptLabel: 'Texas Comptroller of Public Accounts',
    notes: NO_TAX_NOTE,
  },
  {
    code: 'UT',
    name: 'Utah',
    topMarginalRate: 0.0455,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.utah.gov/',
    revenueDeptLabel: 'Utah State Tax Commission',
    notes: 'Utah uses a flat 4.55% rate.',
  },
  {
    code: 'VT',
    name: 'Vermont',
    topMarginalRate: 0.0875,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.vermont.gov/',
    revenueDeptLabel: 'Vermont Department of Taxes',
  },
  {
    code: 'VA',
    name: 'Virginia',
    topMarginalRate: 0.0575,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://www.tax.virginia.gov/',
    revenueDeptLabel: 'Virginia Department of Taxation',
  },
  {
    code: 'WA',
    name: 'Washington',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://dor.wa.gov/',
    revenueDeptLabel: 'Washington Department of Revenue',
    notes:
      'Washington has no broad personal income tax, but it does impose a 7% capital-gains excise tax on long-term gains above the annual standard deduction (~$270k indexed). RSU/ESPP/ISO sale gains may be subject to this if held long-term. See DOR ETA 3242.',
  },
  {
    code: 'WV',
    name: 'West Virginia',
    topMarginalRate: 0.048,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: true,
    revenueDeptUrl: 'https://tax.wv.gov/',
    revenueDeptLabel: 'West Virginia State Tax Department',
  },
  {
    code: 'WI',
    name: 'Wisconsin',
    topMarginalRate: 0.0765,
    supplementalRate: null,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://www.revenue.wi.gov/',
    revenueDeptLabel: 'Wisconsin Department of Revenue',
    notes: 'Wisconsin allows a 30% long-term capital-gain exclusion.',
  },
  {
    code: 'WY',
    name: 'Wyoming',
    topMarginalRate: 0,
    supplementalRate: 0,
    hasPersonalAmt: false,
    taxesLtcgAsOrdinary: false,
    revenueDeptUrl: 'https://revenue.wyo.gov/',
    revenueDeptLabel: 'Wyoming Department of Revenue',
    notes: NO_TAX_NOTE,
  },
];

export function findStateProfile(code: string): StateStockCompProfile | undefined {
  const upper = code.toUpperCase();
  return stateStockCompProfiles.find((s) => s.code === upper);
}

export function listStateProfileCodes(): string[] {
  return stateStockCompProfiles.map((s) => s.code);
}
